# Project: ecommerce-data-analysis
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o btree.o parser.o
LINKOBJ  = main.o btree.o parser.o
LIBS     = -L"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/lib" -L"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib"
INCS     = -I"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/include" -I"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/dbpla/OneDrive/Desktop/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = ecommerce-data-analysis.exe
CXXFLAGS = $(CXXINCS) -std=c99 -g
CFLAGS   = $(INCS) -std=c99 -g
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

btree.o: btree.c
	$(CC) -c btree.c -o btree.o $(CFLAGS)

parser.o: parser.c
	$(CC) -c parser.c -o parser.o $(CFLAGS)
